var os = require('os')

console.log('tmpdir is ', os.tmpdir())
console.log('endianness is ', os.endianness())
console.log('hostname is ', os.hostname())
console.log('type is ', os.type())
console.log('platform is ', os.platform())
console.log('arch is ', os.arch())
console.log('release is ', os.release())
console.log('uptime is ', os.uptime())
console.log('loadavg is ', os.loadavg())
console.log('totalmem is ', os.totalmem())
console.log('freemem is ', os.freemem())
console.log('cpus is ', os.cpus())
console.log('networkInterfaces is ', os.networkInterfaces())
